feat: add generate-revisions command

diff --git a/task b/task
--- a/task
+++ b/task
@@ -138,6 +138,41 @@ function get-module-version() {
     fi
 }
 
+function generate-revisions() {
+    # Delete the existing revisions.md file
+    rm -f revisions.md
+
+    echo "# Odoo Revisions" > revisions.md
+    echo >> revisions.md
+    echo "A Odoo revision is a snapshot of git references of the Odoo source and modules at a specific date." >> revisions.md
+    echo >> revisions.md
+    echo "For each major release there are multiple revisions." >> revisions.md
+    echo >> revisions.md
+
+    declare -A revisions
+
+    # Loop through files in the scripts/ directory that match the pattern
+    for file in scripts/odoo_revision_*; do
+        if [[ -f "$file" ]]; then
+            revision=$(basename "$file" | sed 's/odoo_revision_//')
+            major_version=$(echo "$revision" | cut -d'.' -f1-2)
+
+            if [[ -z "${revisions[$major_version]}" ]]; then
+                revisions[$major_version]="## $major_version"
+            fi
+
+            revisions[$major_version]+=$'\n\n'
+            revisions[$major_version]+="[$revision](./$file)"
+        fi
+    done
+
+    # Sort the versions and write to the markdown file
+    for version in $(echo "${!revisions[@]}" | tr ' ' '\n' | sort -V); do
+        echo -e "${revisions[$version]}" >> revisions.md
+        echo >> revisions.md
+    done
+}
+
 function init-venv() {
     if [ ! -d "venv$GIT_BRANCH" ]; then
         echo "Init venv$GIT_BRANCH with $(python --version)."
@@ -1066,6 +1101,19 @@ function update-docs() {
             done
         done
     done
+
+    generate-revisions
+    if ! grep -q "\*\*Odoo Revisions\*\*" README.md; then
+        echo "Odoo Revisions section not found in README.md."
+        exit 1
+    fi
+
+    if ! grep -q "\*\*\[Odoo Revisions\](revisions.md)\*\*" README.md; then
+        echo "Linking revisions.md in README.md"
+        sed -i 's/\*\*Odoo Revisions\*\*/\*\*\[Odoo Revisions\](revisions.md)\*\*/' README.md
+    else
+        echo "Link to revisions.md already exists in README.md"
+    fi
     echo -e "export default [$SIDEBAR_ENTRIES]" > .vuepress/sidebar.js
 }
 
