sync from 14.0

diff --git a/task b/task
--- a/task
+++ b/task
@@ -361,6 +361,7 @@ function checkout() {
     for SUBMODULE in $SUBMODULES; do
         CWD=$(pwd)
         cd $SUBMODULE
+        git stash
         git switch $1
         cd $CWD
     done
@@ -521,6 +522,15 @@ function lint-snippets() {
         PRIORITY=$(echo 'cat //data/@priority' | xmllint --shell $FILE | awk -F'[="]' '!/>/{print $(NF-1)}')
         MODULE_NAME=$(echo $INHERIT_ID | cut -d. -f 1 )
         XML_ID=$(echo $INHERIT_ID | cut -d. -f 2 )
+
+        # Check filename 
+        COUNT_DOTS=$(echo $FILENAME | grep -o "\." | wc -l)
+        if [ $COUNT_DOTS -ge 4 ]; then
+            echo "Linting failed for $FILE"
+            echo "Dots count: $COUNT_DOTS"
+            echo "  Filename: $SNIPPET_MODULE.$REPORT"
+            exit 1
+        fi
 
         # Check if inherit id matches the filename
         if [ -n "$INHERIT_ID" ]; then
@@ -713,14 +723,19 @@ function update-docs() {
         for FILE in $FILES; do
             FILENAME=$(basename $FILE)
             SNIPPET_MODULE=$(echo $FILENAME | cut -d. -f1)
-            REPORT=$(echo $FILENAME | cut -d. -f2)
+            XML_ID=$(echo $FILENAME | cut -d. -f2)
             EDIT=$(echo $FILENAME | cut -d. -f3)
+
+            EDIT_TITLE=$(echo $EDIT | sed 's/_/ /g') # Replace underline with space
+            EDIT_TITLE=$(echo $EDIT_TITLE | sed -r 's/\<./\U&/g') # Uppercase first letter after space
+
+            XML_ID_TITLE=$(echo $XML_ID | sed 's/_/ /g') # Replace underline with space
+            XML_ID_TITLE=$(echo $XML_ID_TITLE | sed -r 's/\<./\U&/g') # Uppercase first letter after space
 
             # Group by modules
             if [[ "$MODULE" = "$SNIPPET_MODULE" ]]; then
-                echo "### $(echo $EDIT | sed 's/_/ /g')  " >> snippets.md
-                echo "Report: $REPORT  " >> snippets.md
-                echo "ID: \`mint_system.$SNIPPET_MODULE.$REPORT.$EDIT\`  " >> snippets.md
+                echo "### $XML_ID_TITLE: $EDIT_TITLE  " >> snippets.md
+                echo "ID: \`mint_system.$SNIPPET_MODULE.$XML_ID.$EDIT\`  " >> snippets.md
                 echo "Link: [$FILE]($PATH_URL/$FILE)" >> snippets.md
                 echo "" >> snippets.md
             fi
